#!/usr/bin/env python3
"""
scripts/setup_local.py
────────────────────────
One-command local environment setup.

Steps:
  1. Verify Python ≥ 3.11
  2. Create/check .env file
  3. Generate cryptographic keys
  4. Verify PostgreSQL connection
  5. Create database tables
  6. (Optional) Load test data

Run: python scripts/setup_local.py [--with-test-data] [--members 2000]
"""
import argparse
import os
import secrets
import subprocess
import sys
from pathlib import Path

# Ensure we're in the project root
PROJECT_ROOT = Path(__file__).parent.parent
os.chdir(PROJECT_ROOT)
sys.path.insert(0, str(PROJECT_ROOT))


def check_python_version():
    print("🔍 Checking Python version...")
    if sys.version_info < (3, 11):
        print(f"❌ Python 3.11+ required. Found: {sys.version}")
        sys.exit(1)
    print(f"✅ Python {sys.version_info.major}.{sys.version_info.minor}")


def setup_env_file():
    print("\n🔑 Setting up .env file...")
    env_path = PROJECT_ROOT / ".env"

    if env_path.exists():
        print("⚠️  .env file already exists — skipping key generation.")
        print("   To regenerate keys, delete .env and run this script again.")
        return

    # Generate keys
    from cryptography.fernet import Fernet
    fernet_key = Fernet.generate_key().decode()
    hmac_key = secrets.token_hex(32)
    jwt_key = secrets.token_hex(32)

    env_content = f"""# Auto-generated by setup_local.py — DO NOT COMMIT TO GIT
# ─── Database ─────────────────────────────────────────────────────
DATABASE_URL=postgresql://sacco_user:sacco_pass@localhost:5432/sacco_experiments
DATABASE_TEST_URL=postgresql://sacco_user:sacco_pass@localhost:5432/sacco_experiments_test

# ─── Security (auto-generated) ───────────────────────────────────
TOKENIZATION_SECRET_KEY={fernet_key}
HMAC_SECRET_KEY={hmac_key}
JWT_SECRET_KEY={jwt_key}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=480

# ─── Application ─────────────────────────────────────────────────
APP_ENV=development
APP_NAME=SACCO Retention Analysis System
LOG_LEVEL=INFO
MIN_COHORT_DISPLAY_SIZE=30

# ─── Dashboard ────────────────────────────────────────────────────
STREAMLIT_SERVER_PORT=8501
STREAMLIT_SERVER_ADDRESS=localhost

# ─── API ──────────────────────────────────────────────────────────
API_HOST=127.0.0.1
API_PORT=8000
"""
    env_path.write_text(env_content)
    print(f"✅ .env created with fresh cryptographic keys")
    print(f"   ⚠️  IMPORTANT: Add .env to .gitignore before committing anything!")


def check_gitignore():
    print("\n🔒 Checking .gitignore...")
    gitignore_path = PROJECT_ROOT / ".gitignore"
    required_entries = [".env", "*.pyc", "__pycache__/", "*.egg-info/", ".venv/", "venv/"]

    if not gitignore_path.exists():
        gitignore_path.write_text("\n".join(required_entries) + "\n")
        print("✅ Created .gitignore")
    else:
        content = gitignore_path.read_text()
        missing = [e for e in required_entries if e not in content]
        if missing:
            with gitignore_path.open("a") as f:
                f.write("\n" + "\n".join(missing) + "\n")
            print(f"✅ Added missing entries to .gitignore: {missing}")
        else:
            print("✅ .gitignore OK")


def check_postgresql():
    print("\n🐘 Checking PostgreSQL connection...")
    try:
        from dotenv import load_dotenv
        load_dotenv()

        db_url = os.getenv("DATABASE_URL")
        if not db_url:
            print("❌ DATABASE_URL not set in .env")
            return False

        import psycopg2
        from urllib.parse import urlparse
        parsed = urlparse(db_url)

        conn = psycopg2.connect(
            host=parsed.hostname,
            port=parsed.port or 5432,
            user=parsed.username,
            password=parsed.password,
            database=parsed.path.lstrip("/"),
        )
        conn.close()
        print("✅ PostgreSQL connection successful")
        return True
    except Exception as e:
        print(f"❌ PostgreSQL connection failed: {e}")
        print("\n   To set up PostgreSQL locally:")
        print("   1. Install PostgreSQL: https://www.postgresql.org/download/")
        print("   2. Create database and user:")
        print("      psql -U postgres")
        print("      CREATE USER sacco_user WITH PASSWORD 'sacco_pass';")
        print("      CREATE DATABASE sacco_experiments OWNER sacco_user;")
        print("      CREATE DATABASE sacco_experiments_test OWNER sacco_user;")
        return False


def create_tables():
    print("\n🗄️  Creating database tables...")
    try:
        from app.core.database import get_engine
        from app.models.db_models import Base

        engine = get_engine()
        Base.metadata.create_all(bind=engine)
        print("✅ All database tables created")
    except Exception as e:
        print(f"❌ Table creation failed: {e}")
        raise


def load_test_data(n_members: int):
    print(f"\n🌱 Loading {n_members:,} test members...")
    result = subprocess.run(
        [sys.executable, "scripts/generate_test_data.py",
         f"--members={n_members}", "--seed=42"],
        capture_output=False,
    )
    if result.returncode != 0:
        print("❌ Test data generation failed")
    else:
        print("✅ Test data loaded")


def print_startup_commands():
    print("\n" + "═" * 60)
    print("🚀 Setup complete! Run the system with:")
    print("═" * 60)
    print()
    print("  # Terminal 1 — Start the API server")
    print("  uvicorn app.api.main:app --host 127.0.0.1 --port 8000 --reload")
    print()
    print("  # Terminal 2 — Start the dashboard")
    print("  streamlit run app/dashboard/streamlit_app.py")
    print()
    print("  # API docs (development only)")
    print("  open http://localhost:8000/docs")
    print()
    print("  # Dashboard")
    print("  open http://localhost:8501")
    print()
    print("  # Run tests")
    print("  pytest tests/ -v")
    print()
    print("═" * 60)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Set up SACCO prototype locally")
    parser.add_argument("--with-test-data", action="store_true",
                        help="Load synthetic test data after setup")
    parser.add_argument("--members", type=int, default=2000,
                        help="Number of test members to generate")
    args = parser.parse_args()

    print("══════════════════════════════════════════════════════════")
    print("   SACCO Retention Analysis System — Local Setup")
    print("══════════════════════════════════════════════════════════\n")

    check_python_version()
    setup_env_file()
    check_gitignore()
    pg_ok = check_postgresql()

    if pg_ok:
        create_tables()
        if args.with_test_data:
            load_test_data(args.members)

    print_startup_commands()
